# Generated by Django 2.0 on 2017-12-24 10:21

from django.db import migrations
from django.core.management import call_command


def loadfixture(apps, schema_editor):
    call_command('loaddata', 'links/initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
